FROM ubuntu:22.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        openssh-server \
        iproute2 \
        iputils-ping \
        curl \
        ca-certificates && \
    mkdir /var/run/sshd && \
    echo "root:root" | chpasswd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]

